server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axion_db
    username: postgres
    password: K4rth1ck13@

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true