server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/axion_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 12MB
axion:
  security:
    jwt:
      issuer: axion-api
      access-token-expiration: 900
      refresh-token-expiration: 31536000
  storage:
    local-path: uploads/kyc
    local-path: ./storage/assets
    max-file-size: 10485760
  ai:
    base-url: http://localhost:8090