package com.axion.asset.entity;
public enum AssetDocumentType { PROPERTY_DOCUMENT, REGISTRATION_CERTIFICATE, BANK_STATEMENT, FIXED_DEPOSIT_CERTIFICATE, INVESTMENT_STATEMENT, BUSINESS_DOCUMENT, TAX_DOCUMENT, OWNERSHIP_DOCUMENT, OTHER }
