package com.axion.kyc.entity;
public enum VerificationSignalType { FILE_INTEGRITY, DOCUMENT_TYPE, DOCUMENT_EXPIRY, OCR, IDENTITY_MATCH, FACE_MATCH, DUPLICATE_DOCUMENT, FRAUD_RISK, GRAPH_RISK, EXTERNAL_VERIFICATION }
